### PR TITLE
Robert/350 update dependencies v2

### PR DESCRIPTION
**Pull request by RobertSaylesAND**
[Ticket](https://github.com/isaaccomputerscience/isaac-cs-issues/issues/350)
Attempt two at this to try and isolate whatever failed the workflow last time.

React will require further work beyond a version update (and the addition of `History`), as it reports a list of approximately twenty errors in the code that will need resolving. Reactstrap, SWR and the React submodules either also report errors on runtime or expect the updated react version as a dependency. See [#445](https://github.com/isaaccomputerscience/isaac-cs-issues/issues/445).
Typescript also cannot be updated without further work; this appears to be due to issues with the linting configuration. Specifying an updated eslint dependency to satisfy peer resolution is similarly affected by this issues.
All other dependencies should be up to date as of Monday and some additional ones have been explicitly specified to satisfy peer dependency warnings. See [#446](https://github.com/isaaccomputerscience/isaac-cs-issues/issues/446).

### CODE REVIEW

**Comment by hannah-whelan** [comment]
Testing locally and appears to be running fine, however I did notice a weird visual change that needs fixed:

https://github.com/isaaccomputerscience/isaac-content-editor/assets/114683476/f1a8c517-6a94-4cae-95cb-fbeac5bc6fcc

Presumably caused by something like the bootstrap update

**Comment by RobertSaylesAND** [comment]
Oh. I did think the rotating word in the loading spinner was a bit weird but I didn't realise it was new behaviour. I'll have to look into that...

**Comment by hannah-whelan** [comment]
The Loading spinner is a breaking change with bootstrap 5 relating to the class `sr-only`. It can be fixed by using `visually-hidden` with bootstrap 5, but the problem here is our Loading spinner is using reactstrap 8 (which uses bootstrap 4).  Until we are able to upgrade reactstrap to v9, we should stay on v4 of bootstrap it seems. 

`"bootstrap": "^4.6.2",`

**Comment by RobertSaylesAND** [comment]
Ah, so it is indeed a version mismatch issue. Unfortunately, I think the reactstrap update suffers from the same issues as the other react dependencies, so that will have to wait. I'll roll back the bootstrap version for now then...

**Review by hannah-whelan — APPROVED** [review]

**Pull request merged**
